// <auto-generated />
using System;
using GameZone.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameZone.Migrations
{
    [DbContext(typeof(GameZonerDBContext))]
    [Migration("20260810130421_MigracionSupabase")]
    partial class MigracionSupabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameZone.Modelos.Empresa.Empresa", b =>
                {
                    b.Property<long>("Id_Empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_Empresa"));

                    b.Property<string>("Email_Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre_Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordEncriptada_Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol_Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id_Empresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("GameZone.Modelos.Usuario.Usuario", b =>
                {
                    b.Property<long>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_User"));

                    b.Property<string>("AliasUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordEncriptada")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_User");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GameZone.Modelos.Videojuego", b =>
                {
                    b.Property<long>("Id_Juego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_Juego"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(1500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Id_De_Desarrollador")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id_Juego");

                    b.ToTable("Videojuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
